### ISSUE TITLE
Won't run

### ISSUE THREAD

**Issue by magicodeuk** [jessepinuelas/generator-gulp-wordpress#1]
$ yo gulp-wordpress
undefined:1

SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at E:\nvm\v6.10.0\node_modules\generator-gulp-wordpress\node_modules\wp-cli\lib\commands.js:13:19
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)

**Comment by jessepinuelas** [comment]
@magicodeuk please install gulp-cli globally
